### ISSUE TITLE
stargaze from mercury and venus

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#11]
**objective** 
stargaze from mercury and venus

**result**
work in Earth, Mars, Jupiter, Saturn, Uranus, Neptune
`core.setObserverLocation(long, lat, 425, 1, "", "Mars");`

not work in mercury and venus (no error occurs but the result is not expected)**
`core.setObserverLocation(long, lat, 425, 1, "", "Venus");`

**expected result**
the stars is moving when seeing from mercury or venus

**question**
is it normal 
or
is there some configuration to make the stars moving like stargaze from the earth 
?

best regards

**Comment by beltoforion** [comment]
Just think about it. The default time settings are for Earth, probably 2 h duration and 30 second difference between frames. A Venus day is 116.75 earth days. What motion do you expect to see in half an hour on Venus? Stellarium is working just fine outputting exactly what you instruct it to do. Increase the total observation time to many more days and make the time step at least an earth day long day. Venus and Mercury are spinning very slowly.

But in principle what you are trying to achieve will not work properly because the script computes the time of sunset as the starting time for the script. Sunset as in "Sunset on Earth".  This time has no meaning on Mercury or Venus.

**Comment by beltoforion** [comment]
Should be possible with the new -p parameter
